services:
  server:
    build: .
    ports:
      - 8080:8080
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_DOCKER}
    depends_on:
      postgres_container:
        condition: service_healthy
  postgres_container:
    image: "postgres:15.1-alpine"
    volumes:
      - dbdata:/var/lib/postgres/data
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  dbdata:
