spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_DOMAIN}:5432/postgres?currentSchema=law_office_schema
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: law_office_schema

mybatis:
  mapper-locations: "classpath:mapper/**/*-mapper.xml"

jwt:
  secret: ${JWT_SECRET}
  expirationTimeInSec: 1800
  ableForRefreshTimeInSec: 1000

springdoc:
  swagger-ui:
    operationsSorter: method
  writer-with-order-by-keys: true
