apiVersion: apps/v1
kind: Deployment
metadata:
  name: lawoffice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lawoffice
  template:
    metadata:
      labels:
        app: lawoffice
    spec:
      containers:
        - name: lawoffice
          image: eyakauleva/lawoffice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: pg-configmap
                  key: POSTGRES_DOMAIN
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET

